version: '3'

services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=sakila_db
    volumes:
      - "./sakila_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=password
    volumes:
      - "./data_pgadmin:/var/lib/pgadmin"
    ports:
      - "8080:80"
    networks:
      - pg-network
    depends_on:
      - pgdatabase

  ingest:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - pg-network
    depends_on:
      - pgdatabase

networks:
  pg-network:
    driver: bridge